TotoBobo.Mvc/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using TotoBobo.Mvc.Repository;
using TotoBobo.Mvc.Models;
using TotoBobo.Data.Objects;
using TotoBobo.Mvc.Helper;
using System.IO;
using System.Xml.Linq;
using System.Configuration;

namespace TotoBobo.Mvc.Controllers
{
    [Authorize(Roles="Admin,Sales")]
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            OrderStatisModel model = new OrderStatisModel();
            
            List<Order> orders = OrderRepository.GetAllOrders();
            List<int> customers = new List<int>();
            if (orders != null && orders.Any())
            {
                model.Orders = orders.Count(o => o.Status != OrderStatus.Cancelled);
                model.Products = orders.Sum(o => o.Items.Sum(i => i.Quantity));
                foreach (Order order in orders)
                {
                    if (!customers.Any(c => c == order.CreatedBy.UserId))
                    {
                        customers.Add(order.CreatedBy.UserId);
                    }
                }
                model.Customers = customers.Count;
            }
            return View(model);
        }

        public ActionResult ManageRole()
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem() { Text="All",Value="All"});
            AdminModel model = new AdminModel();
            model.Members = new List<AssignRoleModel>();
            model.SearchModel = new SearchRoleMode();
            //model.CurrentMember = new AssignRoleModel();
            model.Roles = new List<RoleModel>();
            foreach (string role in Roles.GetAllRoles())
            {
                items.Add(new SelectListItem() { Text=role,Value=role});
                model.Roles.Add(new RoleModel() { Role=role});
            }
            ViewData["Role"] = items;
            
            foreach (Data.Objects.User user in UserRepository.GetAllUsers())
            {
                string role = ConstantHelper.CustomerRole;
                if (user.Roles != null&&user.Roles.Any())
                {
                    role = "";
                    foreach (TotoBobo.Data.Objects.UserRole ur in user.Roles)
                    {
                        role = role + ur.RoleName + ",";
                    }
                    if (role.Length > 0)
                        role=role.Substring(0, role.Length - 1);
                }
               
                model.Members.Add(new AssignRoleModel() { UserId=user.UserId,UserName=user.UserName,Role=role});
            }

            return View(model);
        }

        public ActionResult ManageUser()
        {
            ManageUserModel model = new ManageUserModel();
            model.Users = new List<UserModel>();
            model.SearchModel = new SearchUserModel();

            foreach (Data.Objects.User user in UserRepository.GetAllUsers())
            {
                model.Users.Add(new UserModel() { Id = user.UserId, Name = user.UserName });
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult SearchUser(SearchUserModel searchmodel)
        {
            ManageUserModel model = new ManageUserModel();
            model.Users = new List<UserModel>();
            model.SearchModel = new SearchUserModel();
            
            List<User> users = UserRepository.GetAllUsers();
            
            if (searchmodel.Name == null)
            {
                searchmodel.Name = "";
            }

            if (users != null && users.Any(c => c.UserName.ToLower().Contains(searchmodel.Name.ToLower())))
            {
                List<User> userModelList = users.Where(c => c.UserName.ToLower().Contains(searchmodel.Name.ToLower())).ToList();

                foreach (Data.Objects.User user in userModelList)
                {
                    model.Users.Add(new UserModel() { Id = user.UserId, Name = user.UserName });
                }
            }
            return View("ManageUser", model);
        }
        
        public ActionResult EditUser()
        {
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {                                        
                    User user = UserRepository.GetUserById(id);
                    if (user != null)
                    {                        
                        ViewBag.SubTitle = "Edit User";                        
                        EditUserModel model = new EditUserModel()
                        {
                            Id = user.UserId,
                            Name = user.UserName,
                        };
                        return View(model);
                    }
                }
            }

            return RedirectToAction("ManageUser");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUser(EditUserModel model)
        {            
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    ViewBag.SubTitle = "Edit User";                    
                }
            }
            
            if (ModelState.IsValid)
            {
                if (RouteData.Values.Any(v => v.Key == "id"))
                {
                    int id = 0;
                    if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                    {
                        if (model.Id != id)
                        {
                            ModelState.AddModelError("", "Form is injected!");
                            return View(model);
                        }

                        User user = UserRepository.GetUserById(id);

                        bool changePasswordSucceeded;
                        try
                        {
                            string token = WebSecurity.GeneratePasswordResetToken(user.UserName);
                            changePasswordSucceeded = WebSecurity.ResetPassword(token, model.Password);
                        }
                        catch (Exception)
                        {
                            changePasswordSucceeded = false;
                        }

                        if (changePasswordSucceeded)
                        {
                            ModelState.AddModelError("", "Success");
                            return View(model);
                        }
                        else
                        {
                            ModelState.AddModelError("", "The user has not been confirmed yet or The new password is invalid.");
                            return View(model);
                        }                        
                    }
                    else
                    {
                        ModelState.AddModelError("", "Form is injected!");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Form is injected!");
                }

            }

            return View(model);
        }

        [HttpDelete]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteUser()
        {
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    UserRepository.DeleteUser(new User() { UserId = id });
                }
            }
            return RedirectToAction("ManageUser");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchRole(SearchRoleMode searchmodel)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem() { Text = "All", Value = "All" });
            AdminModel model = new AdminModel();
            model.Members = new List<AssignRoleModel>();
            model.SearchModel = searchmodel;
            //model.CurrentMember = new AssignRoleModel();
            model.Roles = new List<RoleModel>();
            foreach (string role in Roles.GetAllRoles())
            {
                items.Add(new SelectListItem() { Text = role, Value = role });
                model.Roles.Add(new RoleModel() { Role = role });
            }
            ViewData["Role"] = items;

            foreach (Data.Objects.User user in UserRepository.GetAllUsers())
            {
                if (!string.IsNullOrEmpty(searchmodel.UserName) && !user.UserName.ToLower().Contains(searchmodel.UserName.ToLower()))
                {
                    continue;
                }
                
                string role = ConstantHelper.CustomerRole;
                if (user.Roles != null && user.Roles.Any())
                {
                    role = "";
                    foreach (TotoBobo.Data.Objects.UserRole ur in user.Roles)
                    {
                        role = role + ur.RoleName + ",";
                    }
                    if (role.Length > 0)
                        role = role.Substring(0, role.Length - 1);
                }

                if (searchmodel.Role != "All" && !role.Contains(searchmodel.Role))
                {
                    continue;
                }

                model.Members.Add(new AssignRoleModel() { UserId = user.UserId, UserName = user.UserName, Role = role });
            }
            return View("ManageRole", model);
        }

        public ActionResult SearchRole()
        {

TotoBobo.Mvc/Views/Admin/EditCity.cshtml
@model TotoBobo.Mvc.Models.CityModel
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Manage City";
}

<section class="panel panel-default">
<header class="panel-heading font-bold">@ViewBag.SubTitle in <b>@Model.StateName</b></header>
<div class="panel-body">
     @using (Html.BeginForm("EditCity", "Admin", FormMethod.Post))
     {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @placeholder = "Name",  @class = "form-control" })
        </div>
        
       @Html.HiddenFor(m => m.Id)
       @Html.HiddenFor(m => m.StateId)
       @Html.HiddenFor(m => m.StateName)
        <input type="submit" class="btn btn-sm btn-default" value="Submit"/>
         @Html.ActionLink("Cancel", "ManageCities", new { id = Model.StateId }, new { @class = "btn btn-sm btn-default" });
     }
</div>
</section>
@section Scripts {
    <script type="text/javascript">
        $(function () {
            $(".nav-main > li").each(function () {
                if ($(this).find("span[class='font-bold']").text() == "Manage State") {
                    $(this).addClass("active");
                }
            });
        });
    </script>
}

TotoBobo.Mvc/Views/Admin/EditHomeBanner.cshtml
@model TotoBobo.Mvc.Models.HomeBannerModel
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Banner";
}
@section Styles{
@Styles.Render("~/Content/css/upload")
<style>
  /* For the bootstrapped demos */
  li.alert-success {
      background-color: #DFF0D8;
  }

  li.alert-error {
      background-color: #F2DEDE;
  }

  .alert-error .qq-upload-failed-text {
      display: inline;
  }
</style>
}
<section class="panel panel-default">
<header class="panel-heading font-bold">@ViewBag.SubTitle</header>
<div class="panel-body">
     @using (Html.BeginForm("EditHomeBanner", "Admin", FormMethod.Post, new {@id="homebannerform" }))
     {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <div class="form-group">
            @Html.LabelFor(m => m.TopBanner)
            <br />
            <div class="top_banner_uploader"></div>
        </div>
        <div class="form-group" style="display:none">
            @Html.LabelFor(m => m.TopBannerLink)
            @Html.TextBoxFor(m => m.TopBannerLink, new { @class = "form-control" })
        </div>
         <div class="form-group">
            @Html.LabelFor(m => m.Banner1)
            <br />
            <div class="banner1_uploader"></div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Banner1Link)
            @Html.TextBoxFor(m => m.Banner1Link, new { @class = "form-control" })
        </div>
         <div class="form-group">
            @Html.LabelFor(m => m.Banner2)
            <br />
            <div class="banner2_uploader"></div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Banner2Link)
            @Html.TextBoxFor(m => m.Banner2Link, new { @class = "form-control" })
        </div>
         <div class="form-group">
            @Html.LabelFor(m => m.Banner3)
            <br />
            <div class="banner3_uploader"></div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Banner3Link)
            @Html.TextBoxFor(m => m.Banner3Link, new { @class = "form-control" })
        </div>
       @Html.HiddenFor(m => m.Id)
       @Html.HiddenFor(m => m.GUID, new { @id = "guid" })
        <input type="submit" class="btn btn-sm btn-default" value="Submit"/>
         @Html.ActionLink("Cancel", "CancelBanner", new { @id = Model.GUID }, new { @class = "btn btn-sm btn-default" });
     }
</div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/totobobo/upload")
    <script type="text/javascript">
        $(document).ready(function () {

            var uploader = $('.top_banner_uploader').fineUploader({
                template: "qq-simple-thumbnails-template",
                thumbnails: {
                    placeholders: {
                        waitingPath: "../../images/assets/waiting-generic.png",
                        notAvailablePath: "../../images/assets/not_available-generic.png"
                    }
                },
                request: {
                    endpoint: '@Url.Action("UploadBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeTopBanner" }
                },
                validation: {
                    allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
                    itemLimit: 1
                },
                session: {
                    endpoint: '@Url.Action("GetBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeTopBanner" }
                },
                deleteFile: {
                    enabled: true, // defaults to false
                    endpoint: '@Url.Action("DeleteBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeTopBanner" }
                }
            });

            uploader.on("complete", function (event, id, name, response, xhr) {
                if (response.success) {
                    setBackground("HomeTopBanner");
                }
            });

            uploader.on("sessionRequestComplete", function (event, response, success, rawData) {
                if (success) {
                    setBackground("HomeTopBanner");
                }
            });

            uploader.on('error', function (event, id, name, errorReason, xhrOrXdr) {
                alert(errorReason);
            });

            var banner1uploader = $('.banner1_uploader').fineUploader({
                template: "qq-simple-thumbnails-template",
                thumbnails: {
                    placeholders: {
                        waitingPath: "../../images/assets/waiting-generic.png",
                        notAvailablePath: "../../images/assets/not_available-generic.png"
                    }
                },
                request: {
                    endpoint: '@Url.Action("UploadBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner1" }
                },
                validation: {
                    allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
                    itemLimit: 1
                },
                session: {
                    endpoint: '@Url.Action("GetBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner1" }
                },
                deleteFile: {
                    enabled: true, // defaults to false
                    endpoint: '@Url.Action("DeleteBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner1" }
                }
            });

            banner1uploader.on("complete", function (event, id, name, response, xhr) {
                if (response.success) {
                    setBackground("HomeBanner1");
                }
            });

            banner1uploader.on("sessionRequestComplete", function (event, response, success, rawData) {
                if (success) {
                    setBackground("HomeBanner1");
                }
            });

            banner1uploader.on('error', function (event, id, name, errorReason, xhrOrXdr) {
                alert(errorReason);
            });

            var banner2uploader = $('.banner2_uploader').fineUploader({
                template: "qq-simple-thumbnails-template",
                thumbnails: {
                    placeholders: {
                        waitingPath: "../../images/assets/waiting-generic.png",
                        notAvailablePath: "../../images/assets/not_available-generic.png"
                    }
                },
                request: {
                    endpoint: '@Url.Action("UploadBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner2" }
                },
                validation: {
                    allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
                    itemLimit: 1
                },
                session: {
                    endpoint: '@Url.Action("GetBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner2" }
                },
                deleteFile: {
                    enabled: true, // defaults to false
                    endpoint: '@Url.Action("DeleteBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner2" }
                }
            });

            banner2uploader.on("complete", function (event, id, name, response, xhr) {
                if (response.success) {
                    setBackground("HomeBanner2");
                }
            });

            banner2uploader.on("sessionRequestComplete", function (event, response, success, rawData) {
                if (success) {
                    setBackground("HomeBanner2");
                }
            });

            banner2uploader.on('error', function (event, id, name, errorReason, xhrOrXdr) {
                alert(errorReason);
            });

            var banner3uploader = $('.banner3_uploader').fineUploader({
                template: "qq-simple-thumbnails-template",
                thumbnails: {
                    placeholders: {
                        waitingPath: "../../images/assets/waiting-generic.png",
                        notAvailablePath: "../../images/assets/not_available-generic.png"
                    }
                },
                request: {
                    endpoint: '@Url.Action("UploadBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner3" }
                },
                validation: {
                    allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
                    itemLimit: 1
                },
                session: {
                    endpoint: '@Url.Action("GetBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner3" }
                },
                deleteFile: {
                    enabled: true, // defaults to false
                    endpoint: '@Url.Action("DeleteBanner", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "HomeBanner3" }
                }
            });

            banner3uploader.on("complete", function (event, id, name, response, xhr) {
                if (response.success) {
                    setBackground("HomeBanner3");
                }
            });

            banner3uploader.on("sessionRequestComplete", function (event, response, success, rawData) {
                if (success) {
                    setBackground("HomeBanner3");
                }
            });

            banner3uploader.on('error', function (event, id, name, errorReason, xhrOrXdr) {
                alert(errorReason);
            });

            $('#homebannerform').submit(function (e) {
                //$("#descriptionfield").val($("#editor").html());
                return true;
            });

            //$("#editor").html($("#descriptionfield").val());

            $(".nav-main > li").each(function () {
                if ($(this).find("span[class='font-bold']").text() == "Manage Banner") {
                    $(this).addClass("active");
                }
            });
        });

        function setBackground(banner) {
            $(".qq-upload-fail").remove();
        }
</script>
<script type="text/template" id="qq-simple-thumbnails-template">
  <div class="qq-uploader-selector qq-uploader">
    <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
      <span>Drop files here to upload</span>
    </div>
    <div class="qq-upload-button-selector qq-upload-button">
      <div>Upload a file</div>
    </div>
    <span class="qq-drop-processing-selector qq-drop-processing">
      <span>Processing dropped files...</span>
      <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
    </span>
    <ul class="qq-upload-list-selector qq-upload-list">
      <li style="margin-bottom:5px;">
        <div class="qq-progress-bar-container-selector">
          <div class="qq-progress-bar-selector qq-progress-bar"></div>
        </div>
        <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
        <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
        <span class="qq-edit-filename-icon-selector qq-edit-filename-icon"></span>
        <span class="qq-upload-file-selector qq-upload-file"></span>
        <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
        <span class="qq-upload-size-selector qq-upload-size"></span>
        <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">Cancel</a>
        <a class="qq-upload-retry-selector qq-upload-retry" href="#">Retry</a>
        <a class="qq-upload-delete-selector qq-upload-delete" href="#">Delete</a>
        <a class="qq-upload-markasdefault" href="javascript:void" style="display:none">Mark as Default</a>
        <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
        <span class="qq-upload-failed-text"></span>
        <label class="label bg-info m-l-xs pull-right default-flag" style="display:none">Default</label>
      </li>
    </ul>
  </div>
</script>
}

TotoBobo.Mvc/Views/Admin/EditPayment.cshtml
@model TotoBobo.Mvc.Models.PaymentModel
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Edit Payment";
}
@section Styles{
@Styles.Render("~/Content/css/upload")
<style>
  /* For the bootstrapped demos */
  li.alert-success {
      background-color: #DFF0D8;
  }

  li.alert-error {
      background-color: #F2DEDE;
  }

  .alert-error .qq-upload-failed-text {
      display: inline;
  }
</style>
}
<section class="panel panel-default">
<header class="panel-heading font-bold">@ViewBag.SubTitle</header>
<div class="panel-body">
     @using (Html.BeginForm("EditPayment", "Admin", FormMethod.Post))
     {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @placeholder = "Name",  @class = "form-control" })
        </div>
         <div class="form-group">
            @Html.LabelFor(m => m.IsEnabled)
            @Html.CheckBoxFor(m =>m.IsEnabled)
        </div>
         <div class="form-group">
            @Html.LabelFor(m => m.Logo)
            <br />
             * After uploading pictures, please click Submit to save the pictures with the product.
             <br />
             * Only one picture is allowed.
             <div id="thumbnail-fine-uploader"></div>
         </div>
        
       @Html.HiddenFor(m => m.Id)
       @Html.HiddenFor(m => m.GUID, new { @id = "guid" })
        <input type="submit" class="btn btn-sm btn-default" value="Submit"/>
         @Html.ActionLink("Cancel", "CancelPayment", null, new { @class = "btn btn-sm btn-default" });
     }
</div>
</section>
@section Scripts {
    @Scripts.Render("~/bundles/totobobo/upload")
    <script type="text/javascript">
        $(document).ready(function () {

            var uploader = $('#thumbnail-fine-uploader').fineUploader({
                template: "qq-simple-thumbnails-template",
                thumbnails: {
                    placeholders: {
                        waitingPath: "../../images/assets/waiting-generic.png",
                        notAvailablePath: "../../images/assets/not_available-generic.png"
                    }
                },
                request: {
                    endpoint: '@Url.Action("UploadPicture", "Admin")',
                    params: { "guid": $("#guid").val(), "type": "PaymentMethod" }
                },
                validation: {
                    allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
                    itemLimit: 1,
                    sizeLimit: 102400
                },
                session: {
                    endpoint: '@Url.Action("GetPictures", "Admin")',
                    params: { "guid": $("#guid").val() }
                },
                deleteFile: {
                    enabled: true, // defaults to false
                    endpoint: '@Url.Action("DeletePicture", "Admin")',
                    params: { "guid": $("#guid").val() }
                }
            });

            $(function () {
                $(".nav-main > li").each(function () {
                    if ($(this).find("span[class='font-bold']").text() == "Payment Method") {
                        $(this).addClass("active");
                    }
                });
            });
        });

     
</script>
<script type="text/template" id="qq-simple-thumbnails-template">
  <div class="qq-uploader-selector qq-uploader">
    <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
      <span>Drop files here to upload</span>
    </div>
    <div class="qq-upload-button-selector qq-upload-button">
      <div>Upload a file</div>
    </div>
    <span class="qq-drop-processing-selector qq-drop-processing">
      <span>Processing dropped files...</span>
      <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
    </span>
    <ul class="qq-upload-list-selector qq-upload-list">
      <li style="margin-bottom:5px;">
        <div class="qq-progress-bar-container-selector">
          <div class="qq-progress-bar-selector qq-progress-bar"></div>
        </div>
        <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
        <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
        <span class="qq-edit-filename-icon-selector qq-edit-filename-icon"></span>
        <span class="qq-upload-file-selector qq-upload-file"></span>
        <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
        <span class="qq-upload-size-selector qq-upload-size"></span>
        <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">Cancel</a>
        <a class="qq-upload-retry-selector qq-upload-retry" href="#">Retry</a>
        <a class="qq-upload-delete-selector qq-upload-delete" href="#">Delete</a>
        <a class="qq-upload-markasdefault" href="javascript:void" style="display:none">Mark as Default</a>
        <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
        <label class="label bg-info m-l-xs pull-right default-flag" style="display:none">Default</label>
      </li>
    </ul>
  </div>
</script>
<script type="text/template" id="qq-template-bootstrap">
  <div class="qq-uploader-selector qq-uploader span12">
    <div class="qq-upload-drop-area-selector qq-upload-drop-area span12" qq-hide-dropzone>
      <span>Drop files here to upload</span>
    </div>
    <div class="qq-upload-button-selector qq-upload-button btn btn-success">
      <div><i class="icon-upload icon-white"></i> Upload a file</div>
    </div>
    <span class="qq-drop-processing-selector qq-drop-processing">
      <span>Processing dropped files...</span>
      <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
    </span>
    <ul class="qq-upload-list-selector qq-upload-list" style="margin-top: 10px; text-align: center;">
      <li>
        <div class="qq-progress-bar-container-selector">
          <div class="qq-progress-bar-selector qq-progress-bar"></div>
        </div>
        <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
        <span class="qq-upload-file-selector qq-upload-file"></span>
        <span class="qq-upload-size-selector qq-upload-size"></span>
        <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">Cancel</a>
        <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
      </li>
    </ul>
  </div>
</script>
}

TotoBobo.Mvc/Views/Admin/_SearchCategory.cshtml
@model TotoBobo.Mvc.Models.SearchCategoryModel

 @using (Html.BeginForm("SearchCategory", "Admin")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

     <div class="col-sm-4">  
        <div class="input-group text-sm">
                @Html.TextBoxFor(m => m.Name, new { @class = "input-sm form-control", @placeholder = "Name" })
            <div class="input-group-btn">
                <input class="btn btn-sm btn-default" type="submit" value="Search"  />
            </div>
        </div>
    </div>
        
 }

TotoBobo.Mvc/Views/Admin/_SearchProductPartial.cshtml
 @model TotoBobo.Mvc.Models.SearchProductModel

 <div class="row wrapper">
 @using (Html.BeginForm("SearchProduct", "Admin")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <div class="col-sm-3">
        @Html.DropDownListFor(m => m.CategoryId, null, new { @class = "input-sm form-control input-s-sm inline v-middle", @style = "width:100%" })
    </div>
    <div class="col-sm-3">
        @Html.TextBoxFor(m => m.Name, new { @class = "input-sm form-control", @placeholder = "Name", @style = "width:100%" })
    </div>
    <span class="input-group-btn">
        <input class="btn btn-sm btn-default" type="submit" value="Search"  style="margin-left:15px" />
    </span>       
 }
</div>