TotoBobo.Mvc/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TotoBobo.Mvc.Helper;
using System.Security.Cryptography;
using TotoBobo.Mvc.Models;
using TotoBobo.Mvc.Repository;
using TotoBobo.Data.Objects;
using WebMatrix.WebData;

namespace TotoBobo.Mvc.Controllers
{
    public class CartController : Controller
    {
        //
        // GET: /Cart/

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddToCart(CartItem item)
        {
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    if (id > 0 && item!=null&&item.Quantity>0)
                    {
                        try
                        {
                            item.ProductId = id;
                            item.SessionId = Session.SessionID;
                            item.Id = 0;
                            if (HttpContext.Request.QueryString["type"] == "hamper")
                            {
                                item.IsHamper = true;
                            }
                            CartRepository.AddToCart(item);
                            return Json(new { success = true }, "text/plain", JsonRequestBehavior.AllowGet);
                        }
                        catch (Exception ex)
                        {
                            return Json(new { success = false, message = ex.Message }, "text/plain", JsonRequestBehavior.AllowGet);
                        }
                    }
                }
            }
            return Json(new { success = false }, "text/plain", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Add(int qty)
        {
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    if (id > 0 && qty > 0)
                    {
                        try
                        {
                            CartRepository.ChangeQty(id, qty);
                            return Json(new { success = true }, "text/plain", JsonRequestBehavior.AllowGet);
                        }
                        catch (Exception ex)
                        {
                            return Json(new { success = false, message = ex.Message }, "text/plain", JsonRequestBehavior.AllowGet);
                        }
                        //string cart = "";
                        //HttpCookie existing = Request.Cookies[CartDataProtector.EncryptStringToBytes_Aes(Session.SessionID)];
                        //if (existing != null)
                        //{
                        //    cart = CartDataProtector.DecryptStringFromBytes_Aes(existing.Value);
                        //}
                        //string[] items = cart.Split('|');
                        //Dictionary<int, int> dicItems = new Dictionary<int, int>();
                        //foreach (string item in items)
                        //{
                        //    if (string.IsNullOrEmpty(item))
                        //        continue;
                        //    string[] pair = item.Split(',');
                        //    if (pair.Length > 1)
                        //    {
                        //        int pid = 0;
                        //        int quantity = 0;
                        //        if (int.TryParse(pair[0], out pid) && int.TryParse(pair[1], out quantity) && pid > 0 && quantity > 0)
                        //        {
                        //            if (dicItems.Keys.Any(i => i == pid))
                        //            {
                        //                dicItems[pid] += quantity;
                        //            }
                        //            else
                        //            {
                        //                dicItems.Add(pid, quantity);
                        //            }
                        //        }
                        //    }
                        //}

                        //Product product = ProductRepository.GetProductById(id);
                        //int total = qty;
                        //if (dicItems.Keys.Any(i => i == id))
                        //{
                        //    total += dicItems[id];
                        //}
                        //if (product.Quantity < total)
                        //{
                        //    if (qty == 1)
                        //    {
                        //        return Json(new { success = false, message = "Sorry, no more product in stock!" }, "text/plain", JsonRequestBehavior.AllowGet);
                        //    }
                        //    else
                        //    {
                        //        return Json(new { success = false, message = "Sorry, the number you input is larger than what we have in stock!" }, "text/plain", JsonRequestBehavior.AllowGet);
                        //    }
                        //}

                        //if (dicItems.Keys.Any(i => i == id))
                        //{
                        //    dicItems[id] += qty;
                        //}
                        //else
                        //{
                        //    dicItems.Add(id, qty);
                        //}

                        //cart = "";
                        //foreach (var item in dicItems.Keys)
                        //{
                        //    cart = cart + item.ToString() + "," + dicItems[item].ToString() + "|";
                        //}
                        //if (cart.EndsWith("|"))
                        //{
                        //    cart=cart.Remove(cart.Length - 1);
                        //}

                        //cart = CartDataProtector.EncryptStringToBytes_Aes(cart);
                        //HttpCookie cookie = new HttpCookie(CartDataProtector.EncryptStringToBytes_Aes(Session.SessionID), cart);
                        //cookie.Expires = DateTime.Now.AddHours(2);
                        //Response.Cookies.Set(cookie);
                        //return Json(new { success = true }, "text/plain", JsonRequestBehavior.AllowGet);
                    }
                }
            }
            return Json(new { success = false }, "text/plain", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Sub(int qty)
        {
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    if (id > 0 && qty > 0)
                    {
                        try
                        {
                            CartRepository.ChangeQty(id, -qty);
                            return Json(new { success = true }, "text/plain", JsonRequestBehavior.AllowGet);
                        }
                        catch (Exception ex)
                        {
                            return Json(new { success = false, message = ex.Message }, "text/plain", JsonRequestBehavior.AllowGet);
                        }
                        //string cart = "";
                        //HttpCookie existing = Request.Cookies[CartDataProtector.EncryptStringToBytes_Aes(Session.SessionID)];
                        //if (existing != null)
                        //{
                        //    cart = CartDataProtector.DecryptStringFromBytes_Aes(existing.Value);
                        //}
                        //string[] items = cart.Split('|');
                        //Dictionary<int, int> dicItems = new Dictionary<int, int>();
                        //foreach (string item in items)
                        //{
                        //    if (string.IsNullOrEmpty(item))
                        //        continue;
                        //    string[] pair = item.Split(',');
                        //    if (pair.Length > 1)
                        //    {
                        //        int pid = 0;
                        //        int quantity = 0;
                        //        if (int.TryParse(pair[0], out pid) && int.TryParse(pair[1], out quantity) && pid > 0 && quantity > 0)
                        //        {
                        //            if (dicItems.Keys.Any(i => i == pid))
                        //            {
                        //                dicItems[pid] += quantity;
                        //            }
                        //            else
                        //            {
                        //                dicItems.Add(pid, quantity);
                        //            }
                        //        }
                        //    }
                        //}

                        //if (dicItems.Keys.Any(i => i == id))
                        //{
                        //    dicItems[id] -= qty;
                        //}

                        //cart = "";
                        //foreach (var item in dicItems.Keys)
                        //{
                        //    if (dicItems[item] == 0)
                        //        continue;
                        //    cart = cart + item.ToString() + "," + dicItems[item].ToString() + "|";
                        //}
                        //if (cart.EndsWith("|"))
                        //{
                        //    cart = cart.Remove(cart.Length - 1);
                        //}

                        //if (string.IsNullOrEmpty(cart))
                        //{

TotoBobo.Mvc/Views/Product/Cat.cshtml
@model TotoBobo.Mvc.Models.ProductCatModel
@section menu {
    @Html.Partial("_MenuPartial", (string)ViewBag.Menu)
}

@if (!string.IsNullOrEmpty(Model.TopBanner))
{
    <section class="breadcrumb product parallax margbot30" style="background-image:url(@Model.TopBanner)">
			
        <!-- CONTAINER -->
        <div class="container">
	        <h2>@ViewBag.Menu</h2>
        </div><!-- //CONTAINER -->
    </section><!-- //BREADCRUMBS -->
}
else
{
    <section class="breadcrumb product parallax margbot30">
			
        <!-- CONTAINER -->
        <div class="container">
	        <h2>@ViewBag.Menu</h2>
        </div><!-- //CONTAINER -->
    </section><!-- //BREADCRUMBS -->
}


<!-- SHOP BLOCK -->
<section class="shop">
			
	<!-- CONTAINER -->
	<div class="container">
			
		<!-- ROW -->
		<div class="row">
					
			<!-- SIDEBAR -->
			<div id="sidebar" class="col-lg-3 col-md-3 col-sm-3 padbot50">
						
				<!-- CATEGORIES -->
				<div class="sidepanel widget_categories">
					<h3>Categories</h3>
					<ul>
                        @foreach (var item in Model.Categories)
                        {
                            <li>@Html.ActionLink(item.Name, "Cat", new { id = item.Id })</li>
                        }
								
					</ul>
				</div><!-- //CATEGORIES -->
                <div class="sidepanel widget_categories">
					<h3>Brands</h3>
					<ul>
                        @foreach (var item in Model.Brands)
                        {
                            <li>@Html.ActionLink(item.Name, "List", new { bid = item.Id, cid = Model.CategoryId })</li>
                        }
								
					</ul>
				</div><!-- //CATEGORIES -->
			</div><!-- //SIDEBAR -->
					
					
			<!-- SHOP PRODUCTS -->
			<div class="col-lg-9 col-sm-9 padbot20">
                @if (!string.IsNullOrEmpty(Model.Banner1))
                {
                    <div class="banner_block margbot15">
                        @if (!string.IsNullOrEmpty(Model.Banner1Link))
                        {
					        <a class="banner nobord" href="@Model.Banner1Link" ><img src="@Model.Banner1" alt="" /></a>
                        }
                        else
                        {
                            <a class="banner nobord" href="javascript:void(0);" ><img src="@Model.Banner1" alt="" /></a>
                        }
				    </div>
                }

				<!-- SORTING TOVAR PANEL -->
				<div class="sorting_options clearfix">
							
					<!-- COUNT TOVAR ITEMS -->
					<div class="count_tovar_items">
						<p>@ViewBag.CurrentCategory</p>
						<span>@Model.Products.Count.ToString() Items</span>
					</div><!-- //COUNT TOVAR ITEMS -->
							
					<!-- TOVAR FILTER -->
					@*<div class="product_sort">
						<p>SORT BY</p>
						<select class="basic">
							<option value="">Popularity</option>
							<option>Reting</option>
							<option>Date</option>
						</select>
					</div>*@<!-- //TOVAR FILTER -->
							
					<!-- PRODUC SIZE -->
					<div id="toggle-sizes">
						<a class="view_box active" href="javascript:void(0);"><i class="fa fa-th-large"></i></a>
						<a class="view_full" href="javascript:void(0);"><i class="fa fa-th-list"></i></a>
					</div><!-- //PRODUC SIZE -->
				</div><!-- //SORTING TOVAR PANEL -->
						
						
				<!-- ROW -->
				<div class="row shop_block listview">
					@foreach (var item in Model.Products)
                    {	
						<!-- TOVAR1 -->
						<div class="tovar_wrapper col-lg-4 col-md-4 col-sm-6 col-xs-6 col-ss-12 padbot40 listitem" data-price="@item.Price">
                            @if (item.IsOutOfStock)
                            {
                                <div class="tovar_item clearfix tovar_outofstock">
								    <div class="tovar_img">
									    <div class="tovar_img_wrapper">
										    <img class="img" src="@item.Uri" alt="" />
										    <img class="img_h" src="@item.Uri2" alt="" />
									    </div>
									    <div class="tovar_item_btns">
                                            <a class="tovar_view" href="@Url.Action("Detail", new { id = item.Id })">Detailed View</a>
										    <div class="open-project-link"><a class="open-project tovar_view" href="@Url.Action("ProductQV", "Dialog", new { id = item.Id })" ><span>quick</span> view</a></div>
										    <a class="add_bag quick_add" href="javascript:void(0);" data-url="@Url.Action("AddToCart", "Cart", new { id = item.Id })" data-tags="@item.HasTag" ><i class="fa fa-shopping-cart"></i></a>
										
									    </div>
								    </div>
								    <div class="tovar_description clearfix">
                                        @Html.ActionLink(item.Name, "Detail", new { id = item.Id }, new { @class = "tovar_title" })
									    <span class="tovar_price">@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@item.Price</span>
								    </div>
							    </div>
                            }else if (item.IsSale)
                             {
                                <div class="tovar_item clearfix tovar_sale">
								    <div class="tovar_img">
									    <div class="tovar_img_wrapper">
										    <img class="img" src="@item.Uri" alt="" />
										    <img class="img_h" src="@item.Uri2" alt="" />
									    </div>
									    <div class="tovar_item_btns">
                                            <a class="tovar_view" href="@Url.Action("Detail", new { id = item.Id })">Detailed View</a>
										    <div class="open-project-link"><a class="open-project tovar_view" href="@Url.Action("ProductQV", "Dialog", new { id = item.Id })" ><span>quick</span> view</a></div>
										    <a class="add_bag quick_add" href="javascript:void(0);" data-url="@Url.Action("AddToCart", "Cart", new { id = item.Id })"  data-tags="@item.HasTag" ><i class="fa fa-shopping-cart"></i></a>
										
									    </div>
								    </div>
								    <div class="tovar_description clearfix">
                                        @Html.ActionLink(item.Name, "Detail", new { id = item.Id }, new { @class = "tovar_title" })
									    <span class="tovar_price">@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@item.Price</span>
								    </div>
							    </div>
                             }
                             else
                             {
                                <div class="tovar_item clearfix">
								    <div class="tovar_img">
									    <div class="tovar_img_wrapper">
										    <img class="img" src="@item.Uri" alt="" />
										    <img class="img_h" src="@item.Uri2" alt="" />
									    </div>
									    <div class="tovar_item_btns">
                                            <a class="tovar_view" href="@Url.Action("Detail", new { id = item.Id })">Detailed View</a>
										    <div class="open-project-link"><a class="open-project tovar_view" href="@Url.Action("ProductQV", "Dialog", new { id = item.Id })" ><span>quick</span> view</a></div>                                            
										    <a class="add_bag quick_add" href="javascript:void(0);" data-url="@Url.Action("AddToCart", "Cart", new { id = item.Id })"  data-tags="@item.HasTag" ><i class="fa fa-shopping-cart"></i></a>
									    </div>
								    </div>
								    <div class="tovar_description clearfix">
                                        @Html.ActionLink(item.Name, "Detail", new { id = item.Id }, new { @class = "tovar_title" })
									    <span class="tovar_price">@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@item.Price</span>
								    </div>
							    </div>
                             }
							
						</div><!-- //TOVAR1 -->
                    }
							
				</div><!-- //ROW -->
						
				<hr/>
						
				<div class="clearfix">
					<!-- PAGINATION -->
					
					<ul class="pagination">
                    
                    </ul>
					<a class="show_all_tovar" href="javascript:void(0);" style="display:none">show all</a>		
				</div>
						
						
			</div><!-- //SHOP PRODUCTS -->
		</div><!-- //ROW -->
	</div><!-- //CONTAINER -->
</section><!-- //SHOP -->

<!-- TOVAR MODAL CONTENT -->
<div id="modal-body" class="clearfix">
	<div id="tovar_content"></div>
	<div class="close_block"></div>
</div><!-- TOVAR MODAL CONTENT -->

@section Scripts {
    @Scripts.Render("~/bundles/scripts/productview")
    <script type="text/javascript">
        $(function () {
            // $(".listview>.listitem").tsort({ data: 'price' });
            window.itemsPerPage = 6;
            $(".pagination").pagination({
                items: $(".listitem").length,
                itemsOnPage: window.itemsPerPage,
                onPageClick: function (number, event) {
                    $(".listitem").each(function () { $(this).css("display", "none"); });
                    var end = number * window.itemsPerPage - 1;
                    if (end > $(".listitem").length) {
                        end = $(".listitem").length;
                    }

                    for (var i = (number - 1) * window.itemsPerPage; i <= end; i++) {
                        $(".listitem").eq(i).css("display", "block");
                    }
                }
            });

            

            $(function () {
                var maxHeight = 0;
                $(".tovar_description").each(function () {
                    if ($(this).height() > maxHeight) {
                        maxHeight = $(this).height();
                    }
                });
                $(".tovar_description").each(function () {
                    $(this).height(maxHeight);
                });

                $(".pagination").pagination('selectPage', 1);
            });
        });

    </script>
}

TotoBobo.Mvc/Views/Product/Index.cshtml
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Product";
}
@section menu {
    @Html.Partial("_MenuPartial", "Home")
}
<section class="breadcrumb parallax">
			
    <!-- CONTAINER -->
    <div class="container">
	    <h2>MASKS</h2>
    </div><!-- //CONTAINER -->
</section><!-- //BREADCRUMBS -->
		
		
	

TotoBobo.Mvc/Views/Product/List.cshtml
@model TotoBobo.Mvc.Models.ProductCatModel
@section menu {
    @Html.Partial("_MenuPartial", (string)ViewBag.Menu)
}

@if (!string.IsNullOrEmpty(Model.TopBanner))
{
    <section class="breadcrumb product parallax margbot30" style="background-image:url(@Model.TopBanner)">
			
        <!-- CONTAINER -->
        <div class="container">
	        <h2>@ViewBag.Menu</h2>
        </div><!-- //CONTAINER -->
    </section><!-- //BREADCRUMBS -->
}
else
{
    <section class="breadcrumb product parallax margbot30">
			
        <!-- CONTAINER -->
        <div class="container">
	        <h2>@ViewBag.Menu</h2>
        </div><!-- //CONTAINER -->
    </section><!-- //BREADCRUMBS -->
}


<!-- SHOP BLOCK -->
<section class="shop">
			
	<!-- CONTAINER -->
	<div class="container">
			
		<!-- ROW -->
		<div class="row">
					
			<!-- SIDEBAR -->
			<div id="sidebar" class="col-lg-3 col-md-3 col-sm-3 padbot50">
						
				<!-- CATEGORIES -->
				<div class="sidepanel widget_categories">
					<h3>Categories</h3>
					<ul>
                        @foreach (var item in Model.Categories)
                        {
                            <li>@Html.ActionLink(item.Name, "Cat", new { id = item.Id })</li>
                        }
								
					</ul>
				</div><!-- //CATEGORIES -->
                <div class="sidepanel widget_categories">
					<h3>Brands</h3>
					<ul>
                        @foreach (var item in Model.Brands)
                        {
                            <li>@Html.ActionLink(item.Name, "List", new { bid = item.Id, cid = Model.CategoryId })</li>
                        }
								
					</ul>
				</div><!-- //CATEGORIES -->
			</div><!-- //SIDEBAR -->
					
					
			<!-- SHOP PRODUCTS -->
			<div class="col-lg-9 col-sm-9 padbot20">
                @if (!string.IsNullOrEmpty(Model.Banner1))
                {
                    <div class="banner_block margbot15">
                        @if (!string.IsNullOrEmpty(Model.Banner1Link))
                        {
					        <a class="banner nobord" href="@Model.Banner1Link" ><img src="@Model.Banner1" alt="" /></a>
                        }
                        else
                        {
                            <a class="banner nobord" href="javascript:void(0);" ><img src="@Model.Banner1" alt="" /></a>
                        }
				    </div>
                }

				<!-- SORTING TOVAR PANEL -->
				<div class="sorting_options clearfix">
							
					<!-- COUNT TOVAR ITEMS -->
					<div class="count_tovar_items">
						<p>
                        @ViewBag.CurrentCategory
                        @if (!string.IsNullOrEmpty(ViewBag.CurrentCategory) && !string.IsNullOrEmpty(ViewBag.CurrentBrand))
                        {
                            <label>X</label>
                        }
                        @ViewBag.CurrentBrand
                        </p>
						<span>@Model.Products.Count.ToString() Items</span>
					</div><!-- //COUNT TOVAR ITEMS -->
							
					<!-- TOVAR FILTER -->
					@*<div class="product_sort">
						<p>SORT BY</p>
						<select class="basic">
							<option value="">Popularity</option>
							<option>Reting</option>
							<option>Date</option>
						</select>
					</div>*@<!-- //TOVAR FILTER -->
							
					<!-- PRODUC SIZE -->
					<div id="toggle-sizes">
						<a class="view_box active" href="javascript:void(0);"><i class="fa fa-th-large"></i></a>
						<a class="view_full" href="javascript:void(0);"><i class="fa fa-th-list"></i></a>
					</div><!-- //PRODUC SIZE -->
				</div><!-- //SORTING TOVAR PANEL -->
						
						
				<!-- ROW -->
				<div class="row shop_block listview">
					@foreach (var item in Model.Products)
     {	
						<!-- TOVAR1 -->
						<div class="tovar_wrapper col-lg-4 col-md-4 col-sm-6 col-xs-6 col-ss-12 padbot40 listitem" data-price="@item.Price">
                            @if (item.IsOutOfStock)
                            {
                                <div class="tovar_item clearfix tovar_outofstock">
								    <div class="tovar_img">
									    <div class="tovar_img_wrapper">
										    <img class="img" src="@item.Uri" alt="" />
										    <img class="img_h" src="@item.Uri2" alt="" />
									    </div>
									    <div class="tovar_item_btns">
										    <div class="open-project-link"><a class="open-project tovar_view" href="@Url.Action("ProductQV", "Dialog", new { id = item.Id })" ><span>quick</span> view</a></div>
										    <a class="add_bag quick_add" href="javascript:void(0);"  data-tags="@item.HasTag" data-url="@Url.Action("AddToCart", "Cart", new { id = item.Id })" ><i class="fa fa-shopping-cart"></i></a>
										
									    </div>
								    </div>
								    <div class="tovar_description clearfix">
                                        @Html.ActionLink(item.Name, "Detail", new { id = item.Id }, new { @class = "tovar_title" })
									    <span class="tovar_price">@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@item.Price</span>
								    </div>
							    </div>
                            }
                            else if (item.IsSale)
                            {
                                <div class="tovar_item clearfix tovar_sale">
								    <div class="tovar_img">
									    <div class="tovar_img_wrapper">
										    <img class="img" src="@item.Uri" alt="" />
										    <img class="img_h" src="@item.Uri2" alt="" />
									    </div>
									    <div class="tovar_item_btns">
										    <div class="open-project-link"><a class="open-project tovar_view" href="@Url.Action("ProductQV", "Dialog", new { id = item.Id })" ><span>quick</span> view</a></div>
										    <a class="add_bag quick_add" href="javascript:void(0);"  data-tags="@item.HasTag" data-url="@Url.Action("AddToCart", "Cart", new { id = item.Id })" ><i class="fa fa-shopping-cart"></i></a>
										
									    </div>
								    </div>
								    <div class="tovar_description clearfix">
                                        @Html.ActionLink(item.Name, "Detail", new { id = item.Id }, new { @class = "tovar_title" })
									    <span class="tovar_price">@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@item.Price</span>
								    </div>
							    </div>
                            }
                            else
                            {
                                <div class="tovar_item clearfix">
								    <div class="tovar_img">
									    <div class="tovar_img_wrapper">
										    <img class="img" src="@item.Uri" alt="" />
										    <img class="img_h" src="@item.Uri2" alt="" />
									    </div>
									    <div class="tovar_item_btns">
										    <div class="open-project-link"><a class="open-project tovar_view" href="@Url.Action("ProductQV", "Dialog", new { id = item.Id })" ><span>quick</span> view</a></div>
										    <a class="add_bag quick_add" href="javascript:void(0);"  data-tags="@item.HasTag" data-url="@Url.Action("AddToCart", "Cart", new { id = item.Id })" ><i class="fa fa-shopping-cart"></i></a>
										
									    </div>
								    </div>
								    <div class="tovar_description clearfix">
                                        @Html.ActionLink(item.Name, "Detail", new { id = item.Id }, new { @class = "tovar_title" })
									    <span class="tovar_price">@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@item.Price</span>
								    </div>
							    </div>
                            }
							
						</div><!-- //TOVAR1 -->
     }
							
				</div><!-- //ROW -->
						
				<hr/>
						
				<div class="clearfix">
					<!-- PAGINATION -->
					
					<ul class="pagination">
                    
                    </ul>
					<a class="show_all_tovar" href="javascript:void(0);" style="display:none">show all</a>		
				</div>
						
						
			</div><!-- //SHOP PRODUCTS -->
		</div><!-- //ROW -->
	</div><!-- //CONTAINER -->
</section><!-- //SHOP -->

<!-- TOVAR MODAL CONTENT -->
<div id="modal-body" class="clearfix">
	<div id="tovar_content"></div>
	<div class="close_block"></div>
</div><!-- TOVAR MODAL CONTENT -->

@section Scripts {
    @Scripts.Render("~/bundles/scripts/productview")
    <script type="text/javascript">
        $(function () {
            // $(".listview>.listitem").tsort({ data: 'price' });
            window.itemsPerPage = 6;
            $(".pagination").pagination({
                items: $(".listitem").length,
                itemsOnPage: window.itemsPerPage,
                onPageClick: function (number, event) {
                    $(".listitem").each(function () { $(this).css("display", "none"); });
                    var end = number * window.itemsPerPage - 1;
                    if (end > $(".listitem").length) {
                        end = $(".listitem").length;
                    }

                    for (var i = (number - 1) * window.itemsPerPage; i <= end; i++) {
                        $(".listitem").eq(i).css("display", "block");
                    }
                }
            });

            

            $(function () {
                var maxHeight = 0;
                $(".tovar_description").each(function () {
                    if ($(this).height() > maxHeight) {
                        maxHeight = $(this).height();
                    }
                });
                $(".tovar_description").each(function () {
                    $(this).height(maxHeight);
                });
                $(".pagination").pagination('selectPage', 1);
            });
        });
    </script>
}