TotoBobo.Mvc/Controllers/DialogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TotoBobo.Mvc.Models;
using TotoBobo.Data.Objects;
using TotoBobo.Mvc.Repository;
using TotoBobo.Mvc.Helper;

namespace TotoBobo.Mvc.Controllers
{
    public class DialogController : Controller
    {
        //
        // GET: /Dialog/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductQV()
        {
            ProductModel model = new ProductModel() { Pictures = new List<string>() {
                HttpContext.Request.Url.AbsoluteUri.Replace(HttpContext.Request.Url.PathAndQuery, "/images/assets/not_available-generic.png")
            } };
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    if (id > 0)
                    {
                        if (HttpContext.Request.QueryString["type"] == "hamper")
                        {
                            model.ProductType = "hamper";
                            ProductSet product = ProductRepository.GetHamper(id);
                            if (product != null)
                            {
                                model.Id = product.Id;
                                model.Name = product.Name;
                                model.Price = Decimal.Round(product.Price, 2);
                                model.Quantity = 1;
                                model.Inventory = product.Items.Where(p => p.IsMandatory).Select(m => m.Product.Quantity).Min();
                                model.ProductSetItems = product.Items;
                                if (product.Pictures != null && product.Pictures.Any())
                                {
                                    model.Pictures = new List<string>();
                                    string uploadfolder = System.Web.Configuration.WebConfigurationManager.AppSettings["UploadFolder"];
                                    string url = HttpContext.Request.Url.AbsoluteUri.Replace(HttpContext.Request.Url.PathAndQuery, "/" + uploadfolder);
                                    //if (product.Pictures.Count > 4)
                                    //{
                                    //    ProductSetPicture defPic = product.Pictures.FirstOrDefault(p => p.IsDefault);
                                    //    if (defPic == null)
                                    //        defPic = product.Pictures.FirstOrDefault();
                                    //    model.Pictures.Add(url + "/" + defPic.Picture);
                                    //    foreach (ProductSetPicture pp in product.Pictures.Where(p => !p.IsDefault).Take(3))
                                    //    {
                                    //        model.Pictures.Add(url + "/" + pp.Picture);
                                    //    }
                                    //}
                                    //else
                                    //{
                                        foreach (ProductSetPicture pp in product.Pictures)
                                        {
                                            model.Pictures.Add(url + "/" + pp.Picture);
                                        }
                                    //}
                                }
                            }
                        }
                        else
                        {
                            Product product = ProductRepository.GetProductById(id);
                            if (product != null)
                            {
                                model.Id = product.Id;
                                model.Name = product.Name;
                                model.Price = Decimal.Round(product.Price - product.DiscountAmount, 2);
                                model.Quantity = 1;
                                model.Inventory = product.Quantity;
                                model.Tags = product.Tags;
                                model.CountryName = product.Country != null ? product.Country.Name : "";
                                model.CountryPicture = product.Country != null ? product.Country.Picture : "";
                                if (!string.IsNullOrEmpty(model.CountryPicture))
                                {
                                    model.CountryPicture = HttpContext.Request.Url.Scheme + "://" + HttpContext.Request.Url.Authority + "/" + System.Web.Configuration.WebConfigurationManager.AppSettings["UploadFolder"] + "/" + model.CountryPicture;
                                }
                                if (product.Pictures != null && product.Pictures.Any())
                                {
                                    model.Pictures = new List<string>();
                                    string uploadfolder = System.Web.Configuration.WebConfigurationManager.AppSettings["UploadFolder"];
                                    string url = HttpContext.Request.Url.AbsoluteUri.Replace(HttpContext.Request.Url.PathAndQuery, "/" + uploadfolder);
                                    if (product.Pictures.Count > 4)
                                    {
                                        ProductPicture defPic = product.Pictures.FirstOrDefault(p => p.IsDefault);
                                        if (defPic == null)
                                            defPic = product.Pictures.FirstOrDefault();
                                        model.Pictures.Add(url + "/" + defPic.Picture);
                                        foreach (ProductPicture pp in product.Pictures.Where(p => !p.IsDefault).Take(3))
                                        {
                                            model.Pictures.Add(url + "/" + pp.Picture);
                                        }
                                    }
                                    else
                                    {
                                        foreach (ProductPicture pp in product.Pictures)
                                        {
                                            model.Pictures.Add(url + "/" + pp.Picture);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            return View(model);
        }

        public ActionResult CartSummary()
        {
            return View(GetCart());
        }

        public ActionResult CartDetail()
        {
            return View(GetCart());
        }

        public ActionResult CascadeCity()
        {
            List<string> model=new List<string>();
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    State state = MasterDataRepository.GetState(id);
                    if (state != null&&state.Cities != null)
                    {
                        state.Cities.ForEach(c => model.Add(c.Name));
                    }
                }
            }
            
            return View(model.ToArray());
        }

        [Authorize]
        public ActionResult CancelOrder()
        {
            OrderCancelModel model = new OrderCancelModel();
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    model.OrderId = id;
                }
            }

            return View(model);
        }

        [Authorize]
        public ActionResult OrderDetail()
        {
            OrderModel model = null;
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                var obj = Session[RouteData.Values["id"].ToString()];
                if (obj != null)
                {
                    model = obj as OrderModel;
                }
            }
            if (model == null)
                model = new OrderModel() { Items = new List<OrderItemModel>() };
            return View(model);
        }

        // [Authorize(Roles = "QAAdmin")]
        public ActionResult Reply()
        {
            int questionId = 0;
            int.TryParse(RouteData.Values["id"].ToString(), out questionId);
            int repliedTo = 0;
            int.TryParse(HttpContext.Request.QueryString["rep"], out repliedTo);

            return View(new ReplyModel() { QuestionId=questionId,RepliedTo=repliedTo});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reply(ReplyModel model)
        {
            if (ModelState.IsValid)
            {
                Answer item = new Answer()
                {
                    Id = 0,
                    IsAdminReply = false,
                    Body = model.Body,
                    QuestionId = model.QuestionId,
                    RepliedTo = new Answer() { Id = model.RepliedTo,RepliedDate=DateTime.Now },
                    RepliedBy = new User() { UserName=User.Identity.Name},
                    RepliedDate=DateTime.Now,
                    IsDoctorReply=System.Web.Security.Roles.IsUserInRole(User.Identity.Name,ConstantHelper.QAAdminRole)
                };
                QuestionRepository.Reply(item);
            }

            return RedirectToAction("FAQDetail","Home", new { id=model.QuestionId});
        }

        #region helper
        public CartModel GetCart()
        {
            //CartModel model = new CartModel() { Items=new List<CartItemModel>()};
            //Setting setting = SettingRepository.GetSetting();
            //if (setting != null)

TotoBobo.Mvc/Views/Home/AboutUs.cshtml
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - About us";
}
@section menu {
    @Html.Partial("_MenuPartial", "Home")
}
<style>
    .about_us h2, .about_us h3
    {
        text-transform: none;
    }
</style>
<section class="my_account parallax">
	<!-- CONTAINER -->
	<div class="container">
        <div class="my_account_block clearfix">
            <div class="manage about_us">
                <h2>About us</h2>
                <h3>At Ethan & Eian, we only retail products of exclusive quality from premium brands.</h3>
                <h3>As parents ourselves, we understand that sourcing for the best at the most competitive & affordable price is very important. All these starts from the journey of pregnancy to parenthood.</h3>
                <h3>Ethan & Eian strives to provide excellent customer service to each and everyone. Our customization options in getting bundle packs allows room for creativity & necessity, be it as a gift or for own use.</h3>
                <h3>We will be adding on more brands and range of products so stay tuned.</h3>
                <h3>We would also like to hear from you any brands or suggestions you might have in mind. So do drop us an email at kelissa@ethaneian.com</h3>
            </div>
        </div>
    </div>
</section>

TotoBobo.Mvc/Views/Home/DisclaimerAndLegalNotice.cshtml
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Disclaimer &amp Legal Notice";
}
@section menu {
    @Html.Partial("_MenuPartial", "Home")
}
<style>
    .disclaimer_and_legal_notice h2, .disclaimer_and_legal_notice h3
    {
        text-transform: none;
    }
</style>
<section class="my_account parallax">
	<!-- CONTAINER -->
	<div class="container">
        <div class="my_account_block clearfix">
            <div class="manage disclaimer_and_legal_notice">
                <h2>Disclaimer &amp Legal Notice</h2>
                <h3>This website is the property of Ethan & Eian. It may only be reproduced, disclosed or distributed for non-commercial use with written authorization from Ethan & Eian. Any unauthorized reproduction, disclosure or distribution of copies by any person of any portion of this website may be a violation of the Copyright Law.</h3>
                <h3>With all the material contained in these Web pages, Ethan & Eian has attempted to offer the most timely and accurate information possible. However, inadvertent errors may occur. The information contained in these Web pages is provided without warranty of accuracy. Ethan & Eian reserves the right to discontinue, or change at any time, product features or any information in these Web pages without notice or liabilities.</h3>
                <h3>Many links from this site lead to external resources (websites) which are maintained and hosted by third parties, over which Ethan & Eian has no control and is in no manner responsible.</h3>
            </div>
        </div>
    </div>
</section>

TotoBobo.Mvc/Views/Home/FAQDetail.cshtml
@model TotoBobo.Mvc.Models.FAQModel
@{
    ViewBag.Title = "FAQDetail";
}
@section menu {
    @Html.Partial("_MenuPartial", "Home")
}
<!-- BREADCRUMBS -->
<section class="breadcrumb parallax margbot30"></section>
<!-- //BREADCRUMBS -->
		
		
<!-- PAGE HEADER -->
<section class="page_header">
			
	<!-- CONTAINER -->
	<div class="container">
		<h3 class="pull-left"><b>FAQ</b></h3>
				
		<div class="pull-right">
			<a href="@Url.Action("FAQ")" >Back to FAQ List<i class="fa fa-angle-right"></i></a>
		</div>
	</div><!-- //CONTAINER -->
</section><!-- //PAGE HEADER -->
@if (Model.Doctors != null && Model.Doctors.Any())
                {
                    <section class="brands_carousel">
			
			        <!-- CONTAINER -->
			        <div class="container">
				
				        <!-- JCAROUSEL -->
				        <div class="jcarousel-wrapper">
					
					        <!-- NAVIGATION -->
					        <div class="jCarousel_pagination">
						        <a href="javascript:void(0);" class="jcarousel-control-prev" ><i class="fa fa-angle-left"></i></a>
						        <a href="javascript:void(0);" class="jcarousel-control-next" ><i class="fa fa-angle-right"></i></a>
					        </div><!-- //NAVIGATION -->
					
					        <div class="jcarousel" data-appear-top-offset='-100' data-animated='fadeInUp'>
						        <ul>
                                    @foreach (var doc in Model.Doctors)
                                    {
                                        <li>
                                        <table>
                                        <tr>
                                            <td><a href="@doc.Url" ><img src="@doc.Avator" alt="" style="width:100px" /></a></td>
                                            <td style="width:10px"></td>
                                            <td valign="top" style="max-width:190px">
                                                <label style="font-weight:bold">@doc.Name</label><br />
                                                 <label style="font-weight:bold">Title:</label> @doc.Title<br />
                                                <label style="font-weight:bold">Company:</label>@doc.CompanyName
                                            </td>
                                        </tr>
                                        </table>
                                        
                                        </li>
                                    }
						        </ul>
					        </div>
				        </div><!-- //JCAROUSEL -->
			        </div><!-- //CONTAINER -->
		        </section><!-- //BRANDS -->
                }
<!-- BLOG BLOCK -->
		<section class="blog">
			
			<!-- CONTAINER -->
			<div class="container">
			
				<!-- ROW -->
				<div class="row">
						
						<article class="post blog_post clearfix margbot20" data-appear-top-offset='-100' data-animated='fadeInUp'>
							<div class="post_title" href="javascript:void" >@Model.Question.Title</div>
                            <div style="margin-bottom: 15px;">Category: @Model.Question.QuestionType.Name</div>
							<ul class="post_meta">
								<li><i class="fa fa-user"></i><a href="javascript:void(0);" >@Model.Question.CreatedUserName</a></li>
								<li><i class="fa fa-comments"></i>@Model.Question.Status</li>
							</ul>
							
							<div class="blog_post_content" style="padding:0px">
								@Model.Question.Description
							</div>
							
						</article>
						
						@if (Model.Question.Replies!=null&&Model.Question.Replies.Any())
                        {
						<!-- COMMENTS -->
						<div id="comments" data-appear-top-offset='-100' data-animated='fadeInUp'>
							<h2>Reply (@Model.Question.Replies.Count)</h2>
							<ol>
                                @foreach (var item in Model.Question.Replies)
                                {
								    @Html.Partial("_Answer", item)
                                }
							</ol>
						</div><!-- //COMMENTS -->
                        }
                        
                        @if (Request.IsAuthenticated)
                        {
                            @Html.Action("Reply", "Dialog", new { id = Model.Question.Id, rep = 0 });
                        }
                       
</div>
</div>
</section>
@section Scripts {
<script type="text/javascript">
    $(function () {
        $(".replyform").submit(function () {
            if ($.trim($(this).find(".replybody").val()).length == 0) {
                alert("Please input your comment first!");
                return false;
            }
            return true;
        });

        $(".comment_reply").click(function () {
            var container = $(this).parent().parent().find(".form-container");
            container.load(container.attr("data-url"), function () {
                container.find(".replyform").submit(function () {
                    if ($.trim($(this).find(".replybody").val()).length == 0) {
                        alert("Please input your comment first!");
                        return false;
                    }
                    return true;
                });
            });
        });

        $(".comment_like").click(function () {
            var that=$(this);
            var url = $(this).attr("data-url");
            var $ele=$(this).find(".count").eq(0);
            var number=parseInt($ele.text());
            $.ajax({
                type: "POST",
                url: url,
                contentType: 'application/json; charset=utf-8',
                dataType: "json",
                success: function (data) {
                    if(data.Success){
                       $ele.text((number+1));
                       that.unbind("click");
                    }else{
                       
                    }
                },
                    
            });
        });

        $(".comment_dislike").click(function () {
            var that=$(this);
            var url = $(this).attr("data-url");
            var $ele=$(this).find(".count").eq(0);
            var number=parseInt($ele.text());
            $.ajax({
                type: "POST",
                url: url,
                contentType: 'application/json; charset=utf-8',
                dataType: "json",
                success: function (data) {
                    if(data.Success){
                       $ele.text((number+1));
                        that.unbind("click");
                    }else{
                       
                    }
                },
                    
            });
        });

        $(".comment_choosebest").click(function () {
            var that=$(this);
            var url = $(this).attr("data-url")+"?pid="+$(this).attr("data-id");
            $.ajax({
                type: "POST",
                url: url,
                contentType: 'application/json; charset=utf-8',
                dataType: "json",
                success: function (data) {
                    if(data.Success){
                        $(".best-answer").css("display","none");
                        $(".comment_choosebest").css("display","inline");
                        $(".comment_choosebest").attr("data-id",data.Id);
                        that.parent().find(".comment_choosebest").css("display","none");
                        that.parent().find(".best-answer").css("display","inline");
                    }else{
                       
                    }
                },
                    
            });
        });

    });
    </script>
}

TotoBobo.Mvc/Views/Home/_Answer.cshtml
@model TotoBobo.Data.Objects.Answer
<li>
    <table style="width:100%">
    <tr>
    <td style="width:100px"><div class="pull-left avatar"><a href="javascript:void(0);">
        @if (!string.IsNullOrEmpty(Model.RepliedBy.Avator))
        {
            <img src="@Model.RepliedBy.Avator" style="width:70px" alt="" />
        }
        else
        {
            <img src="../../images/avatar1.jpg" alt="" />
        }
    </a></div></td>
    <td style="">
    <div style="border:1px solid #efefef;padding:10px;">
		<div class="comment_info">
			<a class="comment_author" href="javascript:void(0);" >@Model.RepliedBy.UserName</a>
            @if (Request.IsAuthenticated)
            {
                <a class="comment_reply" href="javascript:void(0);"  style="margin-left:15px"><i class="fa fa-share"></i> Reply</a>
                <a class="comment_dislike" href="javascript:void(0);" style="margin-left:15px" data-url="@Url.Action("Dislike","Home",new{id=Model.Id})"><i class="fa fa-thumbs-down"></i> Dislike (<span class="count">@Model.DislikeCount</span>)</a>
                <a class="comment_like" href="javascript:void(0);"  style="margin-left:15px" data-url="@Url.Action("Like","Home",new{id=Model.Id})"><i class="fa fa-thumbs-up"></i> Like (<span class="count">@Model.LikeCount</span>)</a>
                if (Model.RepliedTo == null&&Model.QuestionCreatorId==WebSecurity.GetUserId(User.Identity.Name))
                {
                    if (!Model.IsBestAnswer)
                    {
                        <a class="comment_choosebest" href="javascript:void(0);" data-id="@Model.BestId"  style="margin-left:15px" data-url="@Url.Action("ChooseBest", "Home", new { id = Model.Id})"><i class="fa fa-check"></i> Mark as Best</a>
                    }
                    else
                    {
                        <a class="comment_choosebest" href="javascript:void(0);" data-id="@Model.BestId"  style="margin-left:15px;display:none" data-url="@Url.Action("ChooseBest", "Home", new { id = Model.Id })"><i class="fa fa-check"></i> Mark as Best</a>
                    }
                }

                if (Model.RepliedTo == null)
                {
                    if (Model.IsBestAnswer)
                    {
                        <a  href="javascript:void(0); " class="best-answer"  style="margin-left:15px;color:red;">Best Answer</a>
                    }
                    else
                    {
                        <a  href="javascript:void(0);" class="best-answer"  style="margin-left:15px;color:red;display:none">Best Answer</a>
                    }
                }
            }
			<div class="clear"></div>
			<div class="comment_date">@Model.RepliedDate.ToShortDateString()</div>
		</div>
		@Html.Raw(Model.Body)
        <div class="form-container" data-url="@Url.Action("Reply", "Dialog", new { id = Model.QuestionId, rep = Model.Id })">
        </div>
	</div>
    </td>
    </tr>
    </table>
	
	
	<div class="clear"></div>
    @if (Model.Replies != null && Model.Replies.Any())
    {
	<ul>
        @foreach (var item in Model.Replies)
        {
		    @Html.Partial("_Answer", item)
        }
	</ul>
    }
</li>