TotoBobo.Mvc/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TotoBobo.Mvc.Models;
using TotoBobo.Data.Objects;
using TotoBobo.Mvc.Repository;
using PayPal.Api.Payments;
using PayPal;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using WebMatrix.WebData;
using TotoBobo.Mvc.Helper;

namespace TotoBobo.Mvc.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        //
        // GET: /Order/

        public ActionResult Index()
        {
            UserOrderModel model = new UserOrderModel() { Orders=new List<OrderModel>()};
            List<Order> orders = OrderRepository.GetUserOrder(User.Identity.Name);
            string uploadfolder = System.Web.Configuration.WebConfigurationManager.AppSettings["UploadFolder"];
            string url = HttpContext.Request.Url.AbsoluteUri.Replace(HttpContext.Request.Url.PathAndQuery, "/" + uploadfolder);
            if (orders != null)
            {
                Setting setting = SettingRepository.GetSetting();
                List<Order> userorders = OrderRepository.GetUserOrder(User.Identity.Name);
                decimal lastTotal = 0;
                if (userorders.Any(o => o.Status == OrderStatus.Paid))
                {
                    lastTotal = userorders.Where(o => o.Status == OrderStatus.Paid).OrderByDescending(o => o.CreatedDate).FirstOrDefault().Total;
                }
                foreach (Order order in orders)
                {
                    OrderModel om = new OrderModel() 
                    { 
                        Id=order.Id,
                        OrderNo=ConstantHelper.GetOrderNumber(order.Id),
                        Total=Decimal.Round(order.Total,2),
                        DeliveryFee=Decimal.Round(order.DeliveryFee,2),
                        CreatedDate=order.CreatedDate,
                        ShippingAddress=order.ShippingAddress,
                        Consignee=order.ShippingAddress.FirstName+" "+order.ShippingAddress.LastName,
                        Status=order.Status.ToString(),
                        Items=new List<OrderItemModel>(),
                        LastTotal=lastTotal,
                        RecordedInDiscount=order.RepeatCustomerDiscount
                    };
                    
                    if (setting != null)
                    {
                        om.TaxRate = setting.TaxRate;
                        om.RepeatCustomerDiscount = setting.RepeatCustomerDiscount;
                    }
                    foreach (OrderItem item in order.Items)
                    {
                        if (item.IsHamper)
                        {
                            OrderItemModel oim = new OrderItemModel()
                            {
                                ProductId = item.ProductSet.Id,
                                ProductName = item.ProductSet.Name
                            };

                            if (item.ProductSet.Pictures != null && item.ProductSet.Pictures.Any())
                            {

                                ProductSetPicture defPic = item.ProductSet.Pictures.FirstOrDefault(p => p.IsDefault);
                                if (defPic == null)
                                    defPic = item.ProductSet.Pictures.FirstOrDefault();
                                oim.Picture = url + "/" + defPic.Picture;

                            }
                            else
                            {
                                oim.Picture = HttpContext.Request.Url.AbsoluteUri.Replace(HttpContext.Request.Url.PathAndQuery, "/images/assets/not_available-generic.png");
                            }
                            om.Items.Add(oim);
                        }
                        else
                        {
                            OrderItemModel oim = new OrderItemModel()
                            {
                                ProductId = item.Product.Id,
                                ProductName = item.Product.Name
                            };

                            if (item.Product.Pictures != null && item.Product.Pictures.Any())
                            {

                                ProductPicture defPic = item.Product.Pictures.FirstOrDefault(p => p.IsDefault);
                                if (defPic == null)
                                    defPic = item.Product.Pictures.FirstOrDefault();
                                oim.Picture = url + "/" + defPic.Picture;

                            }
                            else
                            {
                                oim.Picture = HttpContext.Request.Url.AbsoluteUri.Replace(HttpContext.Request.Url.PathAndQuery, "/images/assets/not_available-generic.png");
                            }
                            om.Items.Add(oim);
                        }
                    }
                    model.Orders.Add(om);
                }
            }
            return View(model);
        }

        public ActionResult Pay()
        {
            PayModel pm = new PayModel() { };
            //List<Product> list = ProductRepository.GetAllProducts();
            if (RouteData.Values.Any(v => v.Key == "id"))
            {
                int id = 0;
                if (int.TryParse(RouteData.Values["id"].ToString(), out id))
                {
                    Order order = OrderRepository.GetOrder(id);
                    if (order != null&&order.Status==OrderStatus.Created)
                    {
                        foreach (OrderItem oi in order.Items)
                        {
                            if (oi.Tags != null&&oi.IsHamper)
                            {
                                foreach (ProductTag pt in oi.Tags)
                                {
                                    if (!oi.Products.Any(p => p.Id == pt.ProductId))
                                    {
                                        ProductSetItem psi = oi.ProductSet.Items.FirstOrDefault(i => i.ProductId == pt.ProductId);
                                        if (psi != null)
                                        {
                                            Product prod = new Product();
                                            prod.Name = psi.Product.Name;
                                            prod.Id = psi.ProductId;

                                            
                                            if (!string.IsNullOrEmpty(pt.Key))
                                            {
                                                prod.Tags = oi.Tags.Where(p => p.ProductId == pt.ProductId).ToList();
                                            }
                                            oi.Products.Add(prod);
                                        }
                                    }
                                }
                            }
                        }
                        pm.Order = order;
                    }
                }
            }
            if (pm.Order == null)
                return RedirectToAction("Index");
            
            return View(pm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Pay(PayModel model)
        {
            Order order = OrderRepository.GetOrder(model.Order.Id);
            if (ModelState.IsValid||model.CreditType=="paypal")
            {
                try
                {
                    var guid = Guid.NewGuid().ToString();
                    Payment pymnt = GetPayment(model, order,guid);
                    // ### Api Context
                    // Pass in a `APIContext` object to authenticate 
                    // the call and to send a unique request id 
                    // (that ensures idempotency). The SDK generates
                    // a request id if you do not pass one explicitly. 
                    // See [Configuration.cs](/Source/Configuration.html) to know more about APIContext..
                    APIContext apiContext = Configuration.GetAPIContext();

                    // Create a payment using a valid APIContext
                    Payment createdPayment = pymnt.Create(apiContext);

                    if (model.CreditType == "paypal")
                    {
                        var links = createdPayment.links;
                        if (links != null && links.Any(l => l.rel == "approval_url"))
                        {
                            OrderRepository.Pay(order.Id, createdPayment.id, guid,OrderStatus.Created);
                            Session.Add(guid, createdPayment.id);
                            return Redirect(links.FirstOrDefault(l => l.rel == "approval_url").href);
                        }
                    }
                    else
                    {
                        OrderRepository.Pay(order.Id, createdPayment.id, null,OrderStatus.Paid);
                        
                        TempData["Message"] = "Your order " + ConstantHelper.GetOrderNumber(order.Id) + " has been paid successfully";
                    }
                }
                catch (PayPal.Exception.PayPalException ex)
                {
                    TempData["Message"] = ex.Message;
                }



                return RedirectToAction("Paid");
            }
            
            model.Order = order;
            return View(model);
        }

        public ActionResult Paid()
        {
            ViewBag.Message = "";

            if (Request.Params["guid"] != null)
            {
                if (Request.Params["PayerID"] != null)
                {
                    string guid = Request.Params["guid"];
                    Order order = OrderRepository.GetOrder(guid);
                    if (order != null)
                    {
                        try
                        {

TotoBobo.Mvc/Views/Order/Detail.cshtml
@model TotoBobo.Mvc.Models.OrderModel
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Manage Order";
}
@section menu {
    @Html.Partial("_MenuPartial", "")
}

<!-- BREADCRUMBS -->
<section class="breadcrumb parallax margbot30"></section>
<!-- //BREADCRUMBS -->
		
		
<!-- PAGE HEADER -->
<section class="page_header">
			
	<!-- CONTAINER -->
	<div class="container">

		<h3 class="pull-left"><b>Order @Model.OrderNo</b></h3>
				
		<div class="pull-right">
			<a href="@Url.Action("Index","Order")" >Back to orders<i class="fa fa-angle-right"></i></a>
		</div>
	</div><!-- //CONTAINER -->
</section><!-- //PAGE HEADER -->
		
		
<!-- SHOPPING BAG BLOCK -->
<section class="shopping_bag_block">
			
	<!-- CONTAINER -->
	<div class="container cartcontainer" >
		<div class="checkout_block" style="border: 2px solid #ccc">
            <div style="padding:20px 0px 00px 20px">
                <label style="font-weight:bold;text-transform:uppercase">Shipping Address</label>
            </div>
            
            <div style="padding:20px" class="defaultaddress">
            @Model.ShippingAddress.FirstName @Model.ShippingAddress.LastName, @Model.ShippingAddress.MobileNo <br />
            @Model.ShippingAddress.Country @Model.ShippingAddress.State @Model.ShippingAddress.City @Model.ShippingAddress.Address1 @Model.ShippingAddress.Postcode
            </div>
           
        </div>	
		<!-- ROW -->
		<div class="row" style="margin-top:30px">
    <!-- CART TABLE -->
            <div class="col-lg-9 col-md-9 padbot10">
                <table class="shop_table">
                    <thead>
                        <tr>
                            <th class="product-thumbnail">
                            </th>
                            <th class="product-name">
                                Item
                            </th>
                            <th class="product-price">
                                Price
                            </th>
                            <th class="product-quantity">
                                Quantity
                            </th>
                            <th class="product-subtotal">
                                Total
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {

                            <tr class="cart_item">
                                <td class="product-thumbnail">
                                    <a href="@Url.Action("Detail", "Product", new { id = item.ProductId,type=item.ProductType })" >
                                        <img src="@item.Picture" width="100px" alt="" /></a>
                                </td>
                                <td class="product-name">
                                    <a href="@Url.Action("Detail", "Product", new { id = item.ProductId, type = item.ProductType })">@item.ProductName</a>
                                    @if (item.IsHamper)
                                    {
					                    <ul class="product_catalog_list" style="padding:0px">
                                        @foreach (var prod in item.Products)
                                        {
                                   
                                                <li data-id="@prod.Id"><a href="javascript:void" style="font-weight:normal;font-size:10px" >@prod.Name</a>
                                                    @if (prod.Tags != null && prod.Tags.Any())
                                                    {
                                                        <ul>
								
                                                        @foreach (var tag in prod.Tags)
                                                        {
                                                            <li>@tag.Key: <span>@tag.Values[0].Value</span></li>
                                                        }
                                
                                                        </ul>
                                                    }
                                            
                                                </li>
                                    
                                        }
						
					                    </ul>
                                    }
                                </td>
                                <td class="product-price">
                                    @TotoBobo.Mvc.ConstantHelper.CurrencySymbol@item.Price
                                </td>
                                <td class="product-quantity" align="center">
                                   @item.Quantity 
                                </td>
                                <td class="product-subtotal">
                                    @TotoBobo.Mvc.ConstantHelper.CurrencySymbol@item.SubTotal
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- //CART TABLE -->
            <div class="col-lg-3 col-md-3 padbot30">
						
		        <!-- BAG TOTALS -->
		        <div class="sidepanel widget_bag_totals your_order_block">
			        <h3>Your Order</h3>
			        <table class="bag_total">
				        <tr class="cart-subtotal clearfix">
					        <th>Sub total</th>
					        <td>@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@Model.Total</td>
				        </tr>
                        <tr class="shipping clearfix">
					        <th>Tax</th>
					        <td>@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@Model.Tax</td>
				        </tr>
				        <tr class="shipping clearfix">
					        <th>SHIPPING</th>
					        <td>@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@Model.DeliveryFee</td>
				        </tr>
                                
				        <tr class="total clearfix">
					        <th>Total</th>
					        <td>@TotoBobo.Mvc.ConstantHelper.CurrencySymbol@Decimal.Round(Model.Total+Model.DeliveryFee+Model.Tax,2)</td>
				        </tr>
			        </table>
                      
		        </div><!-- //REGISTRATION FORM -->
	        </div>
        </div>
        
	</div><!-- //CONTAINER -->
</section><!-- //SHOPPING BAG BLOCK -->
@section Scripts {
<script type="text/javascript">
    $(function () {

        
    });

</script>
}

TotoBobo.Mvc/Views/Order/Index.cshtml
@model TotoBobo.Mvc.Models.UserOrderModel
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Manage Order";
}

@section menu {
    @Html.Partial("_MenuPartial", "")
}
<!-- BREADCRUMBS -->
<section class="breadcrumb parallax margbot30"></section>
<!-- //BREADCRUMBS -->
		
		
<!-- PAGE HEADER -->
<section class="page_header">
			
	<!-- CONTAINER -->
	<div class="container border0 margbot0">
		<h3 class="pull-left"><b>Your orders:</b></h3>
       
	</div><!-- //CONTAINER -->
</section><!-- //PAGE HEADER -->

<section class="checkout_page">
		
	<!-- CONTAINER -->
	<div class="container">
    <div class="row">
					
	<!-- CART TABLE -->
	<div class="col-lg-12 col-md-12 padbot40">
						
		<table class="shop_table">
			<thead>
				<tr>
					<th class="order-items">Products</th>
					<th class="order-no">Order No.</th>
					<th class="product-price">Total</th>
					<th class="product-quantity">Consignee</th>
					<th class="product-subtotal">Created Date</th>
                    <th class="product-subtotal">Status</th>
					<th class="order-operation">Operation</th>
				</tr>
			</thead>
			<tbody>
            @foreach (var item in Model.Orders)
            {
				<tr class="cart_item" valign="middle">
					<td class="order-items">
                    @foreach (var orderitem in item.Items)
                    {
                        <a href="@Url.Action("Detail", "Product", new { id = orderitem.ProductId })" ><img src="@orderitem.Picture" width="100px" alt="" /></a>
                    }
                    </td>
					<td class="order-no">@item.OrderNo</td>
					<td class="product-price">
                        
                        @TotoBobo.Mvc.ConstantHelper.CurrencySymbol@Decimal.Round(item.Status == "Created" ? item.Total + item.DeliveryFee + item.Tax - item.Discount : item.Total + item.DeliveryFee + item.Tax - item.RecordedInDiscount, 2)
                    </td>
					<td class="order-consignee">@item.Consignee</td>				
					<td class="order-createddate">@item.CreatedDate.ToString("yyyy/MM/dd HH:mm:ss")</td>
                    <td class="product-quantity">@item.Status</td>
					<td class="order-operation">
                    @if (item.Status == "Created")
                    {
                        <a href="@Url.Action("Modify", "Order", new { id = item.Id })">Modify</a>
                        <span> &nbsp; &nbsp;&nbsp; | &nbsp;&nbsp;&nbsp; </span>
                        <a href="@Url.Action("CancelOrder", "Dialog", new { id = item.Id })" class="cancelorder" >Cancel</a>
                        <span> &nbsp; &nbsp;&nbsp; | &nbsp;&nbsp;&nbsp; </span>
                        <a href="@Url.Action("Pay", new { id = item.Id })">Pay</a>

                    }
                    else
                    {
                        <a href="@Url.Action("Detail", "Order", new { id = item.Id })">View Detail</a>
                    }
                    </td>
				</tr>
            }				
			</tbody>
		</table>
	</div><!-- //CART TABLE -->
    </div>	
    </div>
</section>
<!-- TOVAR MODAL CONTENT -->
<div id="modal-body" class="clearfix">
	<div id="tovar_content"></div>
	<div class="close_block"></div>
</div><!-- TOVAR MODAL CONTENT -->
@section Scripts {
<script type="text/javascript">
    $(function () {
        var oTable = $('.shop_table').dataTable({
            "sDom": "<'row'<'col-sm-6'l><'col-sm-6'f>r>t<'row'<'col-sm-6'i><'col-sm-6'p>>",
            "sPaginationType": "full_numbers",
            "bFilter": false,
            "bLengthChange": false,
            "iDisplayLength": 5,
            "aoColumnDefs": [{ "bSortable": false, "aTargets": [0] }, { "bSortable": false, "aTargets": [6] }]
        });

        oTable.fnSort([[1, 'desc']]);

        $(".cancelorder").click(function () {
            $("#tovar_content").load($(".cancelorder").attr("href"), function (e) {
                $('#modal-body').addClass('modal-active');
                $('#modal-body').show(function () {
                    $('#tovar_content');
                }).show(2000, function () {
                    $('.element_fade_in').each(function () {
                        $(this).appear(function () {
                            $(this).delay(100).animate({ opacity: 1, right: "0px" }, 1000);
                        });
                    });
                });
                $('#tovar_content').animate({ opacity: 1 });
            });
            return false;
        });
    });
</script>
}

TotoBobo.Mvc/Views/Order/Modify.cshtml
@model TotoBobo.Mvc.Models.OrderModel
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Manage Order";
}
@section menu {
    @Html.Partial("_MenuPartial", "")
}

<!-- BREADCRUMBS -->
<section class="breadcrumb parallax margbot30"></section>
<!-- //BREADCRUMBS -->
		
		
<!-- PAGE HEADER -->
<section class="page_header">
			
	<!-- CONTAINER -->
	<div class="container">
       @if (!string.IsNullOrEmpty(ViewBag.Err))
        {
            <div style="color:Red;margin-bottom:20px;">
            Error occured, details below:<br />
            &nbsp;&nbsp;&nbsp;&nbsp;@ViewBag.Err
            </div>
        }
		<h3 class="pull-left"><b>Order @Model.OrderNo</b></h3>
				
		<div class="pull-right">
			<a href="@Url.Action("Index","Order")" >Back to orders<i class="fa fa-angle-right"></i></a>
		</div>
	</div><!-- //CONTAINER -->
</section><!-- //PAGE HEADER -->
		
		
<!-- SHOPPING BAG BLOCK -->
<section class="shopping_bag_block">
			
	<!-- CONTAINER -->
	<div class="container cartcontainer" >
		<div class="checkout_block" style="border: 2px solid #ccc">
            <div style="padding:20px 0px 00px 20px">
                <label style="font-weight:bold;text-transform:uppercase">Shipping Address</label>
                <a href="javascript:void" style="margin-left:20px" id="editaddresslink">Edit</a>
            </div>
            
            <div style="padding:20px" class="defaultaddress">
            @Model.ShippingAddress.FirstName @Model.ShippingAddress.LastName, @Model.ShippingAddress.MobileNo <br />
            @Model.ShippingAddress.Country @Model.ShippingAddress.State @Model.ShippingAddress.City @Model.ShippingAddress.Address1 @Model.ShippingAddress.Postcode
            </div>
            <div class="editaddressform checkout_form clearfix" style="border: 0px solid #ccc;display:none;">
                <ul>
                    @foreach (var item in Model.Addresses)
                    {
                        <li>
                        @if (item.Id == Model.ShippingAddress.Id)
                        {
                            <input id="ridio-@item.Id" type="radio" name="radio" checked="checked" value="@item.Id" hidden />
                        }
                        else
                        {
                            <input id="ridio-@item.Id" type="radio" name="radio" value="@item.Id" hidden />
                        }
                            <label for="ridio-@item.Id">@item.Country @item.State @item.City @item.Address1 @item.Postcode, @item.MobileNo @item.FirstName @item.LastName </label>
                        </li>
                    }
                        <li>
                        @if (0 == Model.ShippingAddress.Id)
                        {
                            <input id="ridio-0" type="radio" name="radio" checked="checked" value="0" hidden />
                        }
                        else
                        {
                            <input id="ridio-0" type="radio" name="radio" value="0" hidden />
                        }
					        <label for="ridio-0">Use new address</label>
                        </li>
                </ul>
                <div class="newaddressform" style="display:none">
				    @Html.Partial("_NewOrderAddress", Model)
			    </div>
                 @using (Html.BeginForm("SaveAddress", "Order", FormMethod.Post, new { id = "addressForm" }))
                 {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(m=>m.Id)
                            @Html.HiddenFor(m=>m.Guid)
                            @Html.HiddenFor(m => m.ShippingAddress.Id, new { @class="selectedaddressid"})
                     <input type="submit" class="pull-right btncontinue" value="Save Shipping Address" />
                     }	
            </div>
        </div>	
		<!-- ROW -->
		<div class="container ordercontainer"  data-url="@Url.Action("OrderDetail", "Dialog", new { id=Model.Guid})">
			
		
	    </div><!-- //CONTAINER -->
        
	</div><!-- //CONTAINER -->
</section><!-- //SHOPPING BAG BLOCK -->
@section Scripts {
<script type="text/javascript">
    $(function () {

        $("#editaddresslink").click(function () {
            $(this).css("display", "none");
            $(".defaultaddress").css("display", "none");
            $(".editaddressform").css("display", "block");
        });

        $("input[type='radio']").change(function () {
            $(".selectedaddressid").val($('input[name=radio]:checked').val());
            if ($('input[name=radio]:checked').val() == "0") {
                $(".newaddressform").css("display", "block");
                $(".btncontinue").css("display", "none");
            } else {
                $(".newaddressform").css("display", "none");
                $(".btncontinue").css("display", "block");
            }
        });

        if ($(".selectedaddressid").val() == "0") {
            $(".defaultaddress").css("display", "none");
            $(".editaddressform").css("display", "block");
            $(".newaddressform").css("display", "block");
            $(".btncontinue").css("display", "none");
            $("#editaddresslink").css("display", "none");
        } 

        $('#addressForm').submit(function (e) {
            if (!isNormalInteger($(".selectedaddressid").val())) {
                alert("form is injected");
                return false;
            }
           
            return true;
        });

        $(".statedropdown").on("change.fs", function () {
            var sid = $(this).val();
            $(".cityContainer").children().remove();
            $(".cityContainer").load($(".cityContainer").attr("data-url") + "/" + sid, function (e) {
                $(".cityContainer .basic").fancySelect();
                $("#addressstate").val($(".stateContainer .trigger").text());
                $("#addresscity").val($(".cityContainer .trigger").text());
            })
        });

        $("#addressstate").val($(".stateContainer .trigger").text());
        $("#addresscity").val($(".cityContainer .trigger").text());

        loadOrder();
    });

    function loadOrder() {
        if ($(".ordercontainer").length > 0) {

            $(".ordercontainer").load($(".ordercontainer").attr("data-url"), function () {
                $(".ordercontainer #orderform").submit(function (e) {
                    if ($(".editaddressform").css("display") == "block") {
                        alert("Please save shipping address first!");
                        return false;
                    }

                    if ($(".ordercontainer .shop_table tbody>tr").length == 0) {
                        alert("No items in order");
                        return false;
                    }

                });

                $(".ordercontainer .changecartqty").click(function () {
                    $.ajax({
                        type: "POST",
                        url: $(this).attr("data-url"),
                        dataType: "json",
                        data: { "qty": 1, "guid": $(this).attr("data-id") },
                        success: function (data) {
                            if (data.success) {
                                loadOrder();
                            } else {
                                alert(data.message);
                            }
                        }
                    });
                });

                $(".ordercontainer .removelink").click(function () {
                    $.ajax({
                        type: "POST",
                        url: $(this).attr("data-url"),
                        dataType: "json",
                        data: { "guid": $(this).attr("data-id") },
                        success: function (data) {
                            if (data.success) {
                                loadOrder();
                            } else {
                                alert(data.message);
                            }
                        }
                    });
                });
            });
        }
    }

</script>
}

TotoBobo.Mvc/Views/Order/Paid.cshtml
@{
    ViewBag.Title = TotoBobo.Mvc.ConstantHelper.ApplicationName + " - Paid";
}
@section menu {
    @Html.Partial("_MenuPartial", "")
}

    <!-- BREADCRUMBS -->
<section class="breadcrumb parallax margbot30"></section>
<!-- //BREADCRUMBS -->
		
		
<!-- PAGE HEADER -->
<section class="page_header">
			
	<!-- CONTAINER -->
	<div class="container border0 margbot0">
    <div>
        <h3>
        <b>@ViewBag.Message
        </b>
        </h3>
    </div>
    <div>
        @Html.ActionLink("Manage Orders", "Index", null, new { @class = "btn active", @style = "margin:0px;width:200px;" })
        @Html.ActionLink("Continue Shopping", "Index", "Home",null, new { @class = "btn active", @style = "margin:0px;width:200px; margin-top:20px;margin-bottom:30px;" })
    </div>
    </div>
</section>